"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carga las variables de entorno desde un archivo .env
load_dotenv()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY', 'django-insecure-default-key-for-dev')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 't')

ALLOWED_HOSTS = os.environ.get(
    'ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')


# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'api',
    'chat',
    # Apps de terceros para la API y autenticación
    'rest_framework',
    'rest_framework.authtoken',
    'dj_rest_auth',
    'django.contrib.sites',  # Requerido por allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',  # Requerido para evitar errores de importación
    'dj_rest_auth.registration',
    'django_filters',  # Para la búsqueda y filtrado en la API
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Requerido por django-allauth
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'backend.wsgi.application'
ASGI_APPLICATION = 'backend.asgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL'),
        conn_max_age=600  # Mantiene las conexiones a DB vivas por 10 minutos
    )
}

# Si la URL de Render no está presente, y no estamos en un entorno Render,
# usamos el fallback de tus variables locales (DB_NAME, etc.).
if not os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'traductordb'),
            'USER': os.environ.get('DB_USER', 'postgres'),
            'PASSWORD': os.environ.get('DB_PASSWORD', '123456789'),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# Directorio donde Django recolectará los archivos para producción
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Storage para manejar los archivos estáticos (esencial para collectstatic)
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage' 

# Configuración de archivos media (si los usuarios suben archivos)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Configuraciones para REST Framework y Autenticación (Fase 1) ---

# Requerido por django-allauth
SITE_ID = 1

# Configuración de Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # Usaremos autenticación por Token
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        # Habilitamos el backend de filtros de django-filter
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
}

# --- INICIO DE LA CORRECCIÓN DE allauth ---
# Configuración de django-allauth (usado por dj-rest-auth)
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'

# Opcional: define explícitamente los métodos de login permitidos
ACCOUNT_LOGIN_METHODS = ['username', 'email'] 

# La verificación de correo es ahora obligatoria para poder iniciar sesión.
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
# Durante el desarrollo, los correos se imprimirán en la consola en lugar de ser enviados.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# --- FIN DE LA CORRECCIÓN DE allauth ---

# --- Configuración de CORS ---
# Lista de orígenes permitidos para peticiones CORS

ACCOUNT_EMAIL_CONFIRMATION_HMAC= False

if DEBUG:
    # En desarrollo local
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:5173",  # React/Vite
        "http://localhost:3000",  # React
    ]
else:
    # En producción (Render)
    RENDER_EXTERNAL_URL = os.environ.get("RENDER_EXTERNAL_URL")

    # Permitimos el dominio de Render (HTTP) y el dominio de Render (WebSockets WSS)
    CORS_ALLOWED_ORIGINS = [
        # El dominio principal del Backend para llamadas API
        f"https://{RENDER_EXTERNAL_URL}", 
        # El protocolo WebSocket seguro para el chat
        f"wss://{RENDER_EXTERNAL_URL}",    
        # ¡IMPORTANTE! Si tu Frontend de React está en un dominio diferente de Render
        # (ej: mi-frontend.onrender.com), debes añadir su URL HTTPS aquí
        # "https://mi-frontend-react.onrender.com" 
    ]
    # Si el frontend es un servicio estático separado, su URL debe ir aquí

# Opcional: Permite que el frontend envíe cookies (necesario para sesiones)
CORS_ALLOW_CREDENTIALS = True

# --- Configuración de CHANNELS / WEBSOCKETS ---
REDIS_URL = os.environ.get("REDIS_URL") # Variable que Render inyectará

if REDIS_URL:
    # Configuración de producción usando Redis
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.pubsub.RedisPubSubChannelLayer',
            'CONFIG': {
                "hosts": [REDIS_URL],
            },
        },
    }
else:
    # Fallback para desarrollo (InMemoryChannelLayer si no hay Redis)
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }